### ISSUE TITLE
[8.0] l10n_es_aeat_sii_guipuzcoa: No binding found with the given QName

### ISSUE THREAD

**Issue by ljsalvatierra-binovo** [acysos/odoo-addons#15]
Descripción del error:
`No binding found with the given QName. Available bindings are: {https://egoitza.gipuzkoa.eus/ogasuna/sii/ficheros/SuministroFactRecibidas.wsdl}siiBinding`

En entorno de pruebas, al intentar crear el servicio con la nueva dirección URL de WSDL:
-https://egoitza.gipuzkoa.eus/ogasuna/sii/ficheros/v1.0/SuministroFactRecibidas.wsdl

Debido a que el namespace no ha cambiado, sigue siendo:
-https://egoitza.gipuzkoa.eus/ogasuna/sii/ficheros/SuministroFactRecibidas.wsdl

En entorno de producción no hay problema.

Un saludo y gracias.

**Comment by acysos** [comment]
Hola,

Conocemos el error, resuelta que han cruzados los WSDL de las dos versiones, no deberían haber cambiado la principal como ha hecho nacional hasta que estuviese la 1.1 activa. Me sorprende que te funcione en producción porque el wsdl tiene dos campos que han cambiado y te debería fallar la validación.

Pero el servicio de pruebas esta caído y nos esta impidiendo hacer pruebas.
https://sii-prep.egoitza.gipuzkoa.eus/JBS/HACI/SSII-FACT/ws/fe/SiiFactFEV1SOAP

Saludos

**Comment by acysos** [comment]
Hola,

Acabamos de introducir un cambio en la 10.0 que arregla esto, pero a la espera de que activen el entorno de pruebas.
https://github.com/acysos/odoo-addons/commit/72ddb228301795d1a4b5d2b143344c3add0580b5

Lo pasamos ahora a la 8.0.

Saludos

**Comment by acysos** [comment]
Solucionado https://github.com/acysos/odoo-addons/commit/e2ddf1d79b5556dc9826dfd9ca7baaad0af71ae3

Saludos

**Comment by JuaniFreedoo** [comment]
Creo que ha habido algún cambio estos días en Ogasuna Gipuzkoa, ¿Os funciona bien? 
Estoy recibiendo el error del que hablábamos al principio del hilo

Saludos
