### ISSUE TITLE
[8.0] l10n_es_aeat_sii error descripción automática

### ISSUE THREAD

**Issue by fribelles** [acysos/odoo-addons#18]
Hola,
al generar una consulta con SII configurado con descripción automática, se muestra el siguiente mensaje:

[...]l10n_es_aeat_sii/models/account_invoice.py", line 130, in _get_sii_description_from_lines
    description += line.name + ' - '
TypeError: unsupported operand type(s) for +=: 'bool' and 'unicode'

**Comment by acysos** [comment]
Solucionado

**Comment by fribelles** [comment]
Funciona perfectamente. Gracias por vuestra rápida resolución.
