### ISSUE TITLE
[8.0] l10n_es_aeat_sii - P_IVA21_IC_BC tipo impositivo incorrecto

### ISSUE THREAD

**Issue by fribelles** [acysos/odoo-addons#19]
Tras registrar en SII facturas con el tipo de impuesto "Adquisición Intracomunitaria de bienes corrientes" (principalmente 21%), hemos comprobado que en los datos de desglose que registra la Agencia Tributaria se refleja como tipo impositivo el 100% en lugar del 21% (o 10% o 4%...). Tanto la base imponible como la cuota soportada las expresa correctamente.
La principal diferencia con respecto a otros tipos de impuestos empleados, en los que no se observa este error, es que estos en particular cuentan con 2 impuestos hijos. 
Gracias!

**Comment by acysos** [comment]
Hola,

Ya ha sido corregido en el último commit: https://github.com/acysos/odoo-addons/commit/44c7280b425880e6a263381b13677f80889948f2

Gracias por el reporte

**Comment by fribelles** [comment]
Comprobado, gracias!
