### ISSUE TITLE
[8.0] l10n_es_aeat_sii - Facturas emitidas de servicios no sujetas

### ISSUE THREAD

**Issue by fribelles** [acysos/odoo-addons#21]
Hola,
en las facturas de venta sujetas a IVA que incluyen líneas que son servicios, no se referencian en el desglose  enviado a SII. Esto es: figura siempre como desglose por factura omitiendo el valor de los servicios y presentando solo los importes correspondientes a bienes.
Lo correcto debería ser enviar en formato desglose de bienes y desglose de servicios como apartados independientes en SII.
Hemos comprobado el mapeo de impuestos e inicialmente parece todo bien definido.
Gracias, saludos!

**Comment by fribelles** [comment]
Buenos días, 
creo haber encontrado el problema revisando el código. ¿Puede ser que no se hayan contemplado facturas con servicios no sujetos por reglas de localización? En el mapeo de impuestos podemos ver que se engloban como exentas (S_IVA0_SP_I en SFESSE) y a diferencia de otros módulos, el mapeo denominado SFESNS no se contempla.
Gracias, saludos.

**Comment by acysos** [comment]
Hola,

Se ha corregido en la versión 10.0, se esta procediendo a bajar a la 8.0.

Saludos
