### ISSUE TITLE
[8.0] l10n_es_aeat_sii: factura rectificativa importe total y base imponible distinto signo

### ISSUE THREAD

**Issue by ljsalvatierra-binovo** [acysos/odoo-addons#22]
Se ha creado un PR #23.

Hola, hemos recibido unos avisos por parte de la hacienda Guipuzcoana refiriéndose a facturas de venta rectificativas en entregas intracomunitarias.

Concretamente, se envía el importe total y la base imponible en distinto signo:

```python
# l10n_es_aeat_sii/models/account_invoice.py:616
tipo_desglose = self._get_sii_out_taxes()
# Resultado:
importe_total = -75.0
tipo_desglose = {'DesgloseTipoOperacion': {'Entrega': {'Sujeta': {'Exenta': {'DetalleExenta': {'BaseImponible': 75.0, 'CausaExencion': 'E5'}}}}}}
```

¿Alguien ha tenido problemas similares? Gracias.

**Comment by acysos** [comment]
Hola,

Que versión tenéis, porque en principio en la última se modifica el signo del tipo_desglose cuando es rectificativa:

https://github.com/acysos/odoo-addons/blob/4640b62e9cd5a1bc63893cfb3a7a96d9b8612fa8/l10n_es_aeat_sii/models/account_invoice.py#L618

Saludos

**Comment by ljsalvatierra-binovo** [comment]
Hola, cogí los últimos cambios el pasado viernes.
```bash
4640b62e9cd5a1bc63893cfb3a7a96d9b8612fa8 [FIX] real_estate_base: default value in menu
```
Las pruebas las he realizado con una factura de venta rectificativa e intracomunitaria.

Un saludo y gracias por vuestro tiempo.

**Comment by ljsalvatierra-binovo** [comment]
Hola, 

Hemos podido hablar con el departamento de Hacienda y Finanzas de Gipuzkoa y nos confirman, que a nivel estatal, en una factura rectificativa por diferencias debe ir tanto el importe total como la base imponible en negativo.

Aún no hemos comenzado el desarrollo de un FIX debido a una serie de dudas:

* Sólo se cambia el signo de la base imponible en los siguiente casos:

  * Facturas emitidas Sujetas Bienes (SFESB)
  * Facturas emitidas Sujetas ISP (SFESISP)
  * Facturas emitidas Sujetas Servicios (SFESS)

No conseguimos ver por qué sólo se discriminan estos casos en específico, ¿alguna pista?

Un saludo y gracias de nuevo.

**Comment by ljsalvatierra-binovo** [comment]
Cierro incidencia. Gracias de nuevo por vuestro tiempo.
