### ISSUE TITLE
[8.0] stock_value not installable

### ISSUE THREAD

**Issue by scigghia** [acysos/odoo-addons#3]
i get this error when trying to install stock_value

https://gist.github.com/scigghia/9d4fb8e8c958725166844ad6a13b7c47

**Comment by icrebollo** [comment]
i have solved the problem, but the FIX is not accepted ¿?, you can try my solution.

**Comment by scigghia** [comment]
@icrebollo could you link the fix?

**Comment by acysos** [comment]
@icrebollo The commit is merged: https://github.com/acysos/odoo-addons/commit/cec866f4f50e939401e036ce877858649870af85

Greetings
