### ISSUE TITLE
Migrate module l10_es_coop to Odoo 11.0

### ISSUE THREAD

**Issue by danypr92** [acysos/odoo-addons#32]
Hi!

We are looking to use the module `l10_es_coop` in our instance to manage a cooperative with the Spanish legislation.

Are you maintaining this module? can we propose a PR to migrate this module to 11 or is it deprecate in the new Odoo versions?

Thanks!

**Comment by acysos** [comment]
Hello, we are migrating to official l10n_es

**Comment by danypr92** [comment]
Hi! @acysos thanks! Where can we look at the migration process? is in this repository or in other?

**Comment by acysos** [comment]
No, we go to send the PR to Official Odoo repository

**Comment by danypr92** [comment]
Sorry @acysos, but I do not understand if you open a PR to https://github.com/odoo/odoo or in other place/repository.

I am waiting for this PR and I think that we can help in this work.

**Comment by danypr92** [comment]
Sorry, wrong button...

**Comment by danypr92** [comment]
Hi @acysos!
can you tell us where is the official repo of Odoo? is the [odoo/odoo](github.com/odoo/odoo)

Thanks!

**Comment by acysos** [comment]
Migrated a v11
