### ISSUE TITLE
[12.0] l10n_es_aeat_sii_vizcaya - Error en la instalación 

### ISSUE THREAD

**Issue by manuelviejo** [acysos/odoo-addons#35]
Versión: 12.0
Módulo: l10n_es_aeat_sii_vizcaya

Adjunto el error que se produce al instalar el módulo.
Tengo las dependencias instaladas y actualizadas, en concreto:

- **zeep**: 3.4.0
- **pyOpenSSL**: 17.3.0
- **requests**: 2.9.1

¿Alguien ha tenido algún problema similar?

[error.txt](https://github.com/acysos/odoo-addons/files/3260453/error.txt)

Muchas gracias de antemano.

**Comment by acysos** [comment]
Hola,

No consigo replicar el error? que versión de SII estás usando?

Saludos

**Comment by manuelviejo** [comment]
Hola,

muchas gracias por la respuesta.
Tenía una versión desactualizada del módulo del SII , en concreto la 12.0.1.0.0. He actualizado cogiendo la versión de la tienda de Odoo a la versión 12.0.11.0.1.3.2. Después de varios errores en la instalación ajenos a los módulos implicados, he conseguido tener los dos instalados correctamente.

Un saludo,
Manuel.
