### ISSUE TITLE
[11.0] l10n_es_aeat_mod347_xlsx renombrar __manifest__.py.replace por __manifest__.py

### ISSUE THREAD

**Issue by uolaizola** [acysos/odoo-addons#37]
Buenas tardes,

Observamos que en la versión 11.0 del módulo 10n_es_aeat_mod347_xlsx hay 2 ficheros manifiesto, el módulo no se instala automáticamente con el fichero manifesto por defecto, sin realizar el reemplazamiento.

La pregunta es, si tenéis pensado a corto plazo deja un único fichero manifiesto el que actualmente pone replace, ya que es el que lleva la dependencia del módulo.

Hemos léido el readme y aparentemente vemos que el único motivo era que el modelo 347 no estuviera en odoo apps y vemos que actualmente está disponible

https://www.odoo.com/apps/modules/11.0/l10n_es_aeat_mod347

Gracias por el trabajo realizado.

Saludos,
Ugaitz

**Comment by acysos** [comment]
Hola,

Es correcto, se hizo así porque la dependencia l10n_es_aeat_mod347 no estaba en Odoo Apps cuando se creo este módulo, y no se mostraba en odoo.com/apps

Como ya esta la dependencia, lo hemos cambiado.

https://github.com/acysos/odoo-addons/commit/554ea0dbe6d4a99b6c791fa5020a399216686060

Saludos

**Comment by uolaizola** [comment]
Buenos días,

Perfecto, muchas gracias.

Salud,
Ugaitz
