### ISSUE TITLE
[12.0] l10n_es_aeat_sii_vizcaya - No encuentra modelo: aeat.sii.wsdl

### ISSUE THREAD

**Issue by busmanapps** [acysos/odoo-addons#40]
Hola, al instentar instalar el módulo l10n_es_aeat_sii_vizcaya, desde los archivos .xml (data/aeat_sii_map_data.xml), intenta crear registros de un modelo llamado: aeat.sii.wsdl y me da un error tipo

```
´odoo.tools.convert.ParseError: "aeat.sii.wsdl" while parsing /home/bmv/odoo_12_github/addons/third_party_addons/l10n_es_aeat_sii_vizcaya/data/aeat_sii_map_data.xml:162, near
<record id="wsdl_out_1_0_48" model="aeat.sii.wsdl">
        	<field name="name">SuministroFactEmitidas</field>
        	<field name="key">wsdl_out</field>
        	<field name="wsdl">http://www.bizkaia.eus/ogasuna/sii/documentos/v10/SuministroFactEmitidas.wsdl</field>
        	<field name="sii_map_id" ref="aeat_sii_map_1_0_48"/>
        </record>
```

Tengo ambas dependencias actualizadas (l10n_es y l10n_es_aeat_sii) aproximadamente del mes pasado, pero no encuentro el modelo al que hace referencia (aeat.sii.wsdl). ¿Podrían ayudarme?

Gracias, saludos.

**Comment by acysos** [comment]
@busmanapps he realizado una instalación desde cero y no nos ha dado ningún error. El modelo aeat.sii.wsdl esta en el archivo aeat_sii_map.py

**Comment by busmanapps** [comment]
Hola @acysos.

Sí, está en el repositorio de https://github.com/acysos/odoo-addons. El problema creo que se debe a que tengo en la instalación los módulos del repositorio de https://github.com/OCA/l10n-spain. Entre estos módulos está también el 'l10n_es_aeat_sii', pero sin ese modelo. 

¿Quizás puede quedar pendiente mezclarlo l10n-spain? No me ha parecido ver ningún PR.

Gracias, saludos!

**Comment by acysos** [comment]
@busmanapps estas mezclando versiones diferentes del SII. Este no es compatible con l10n-spain.
