### ISSUE TITLE
error odoo8 instalation farm

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [acysos/odoo-addons#6]
`Odoo Server Error Traceback (most recent call last): File "/opt/odoo/openerp/http.py", line 546, in _handle_exception return super(JsonRequest, self)._handle_exception(exception) File "/opt/odoo/openerp/http.py", line 583, in dispatch result = self._call_function(**self.params) File "/opt/odoo/openerp/http.py", line 319, in _call_function return checked_call(self.db, *args, **kwargs) File "/opt/odoo/openerp/service/model.py", line 118, in wrapper return f(dbname, *args, **kwargs) File "/opt/odoo/openerp/http.py", line 316, in checked_call return self.endpoint(*a, **kw) File "/opt/odoo/openerp/http.py", line 812, in __call__ return self.method(*args, **kw) File "/opt/odoo/openerp/http.py", line 412, in response_wrap response = f(*args, **kw) File "/opt/odoo/addons/web/controllers/main.py", line 948, in call_button action = self._call_kw(model, method, args, {}) File "/opt/odoo/addons/web/controllers/main.py", line 936, in _call_kw return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs) File "/opt/odoo/openerp/api.py", line 268, in wrapper return old_api(self, *args, **kwargs) File "/opt/odoo/openerp/addons/base/module/wizard/base_module_upgrade.py", line 105, in upgrade_module openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True) File "/opt/odoo/openerp/modules/registry.py", line 370, in new openerp.modules.load_modules(registry._db, force_demo, status, update_module) File "/opt/odoo/openerp/modules/loading.py", line 355, in load_modules loaded_modules, update_module) File "/opt/odoo/openerp/modules/loading.py", line 255, in load_marked_modules loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks) File "/opt/odoo/openerp/modules/loading.py", line 156, in load_module_graph registry.setup_models(cr, partial=True) File "/opt/odoo/openerp/modules/registry.py", line 197, in setup_models model._setup_complete(cr, SUPERUSER_ID) File "/opt/odoo/openerp/api.py", line 268, in wrapper return old_api(self, *args, **kwargs) File "/opt/odoo/openerp/api.py", line 372, in old_api result = method(recs, *args, **kwargs) File "/opt/odoo/openerp/models.py", line 3032, in _setup_complete field.setup_triggers(self.env) File "/opt/odoo/openerp/fields.py", line 1743, in setup_triggers self._setup_dependency([self.name], comodel, arg[0].split('.')) File "/opt/odoo/openerp/fields.py", line 624, in _setup_dependency fields = [model._fields[head]] 
KeyError: 'usage'`

**Comment by luizcarlospedrosogomes** [comment]
What is the reason for the error?

**Comment by acysos** [comment]
Hello,

Your installation is in empty odoo??

Saludos

**Comment by luizcarlospedrosogomes** [comment]
hello Saludos

yes empty installation  in odoo8 ubuntu 14.04

**Comment by acysos** [comment]
Hello,

I have upload a new version of farm.

Greetings

**Comment by luizcarlospedrosogomes** [comment]
tanks, working
