### ISSUE TITLE
Odoo 10 - Customer record opening error related to document

### ISSUE THREAD

**Issue by Arsalan88** [acysos/odoo-addons#7]
KeyError: 'document.directory'

**Comment by acysos** [comment]
Hello,

What module show this error?

Greetings

**Comment by Arsalan88** [comment]
Hi,

This object is being called in 2 files.
1. real_estate_base/models/partner.py line 92  dir_obj = self.env['document.directory']
2. real_estate_base/models/rental_agreement.py line 92  dir_obj = self.env['document.directory']

There is no model with name docment.directory in odoo 10, so why it is being used?
I had to comment that part in order to view customers or rental agreement screens.

Greetings

**Comment by LakshminarayananOKN** [comment]
hi @Arsalan88 @acysos  
i also got this error while opening res.partner model form view .. reply me as soon as possible @
![2017-12-18 14-27-26](https://user-images.githubusercontent.com/18413399/34097608-a80b719a-e3ff-11e7-8b48-3e255f9240a0.png)



@Arsalan88 did you solved this issue # # @Arsalan88

**Comment by acysos** [comment]
Hello,

There a new version with this bug corrected and add some changes in zone.

Greetings
